### ISSUE TITLE
[typos.py] pywikibot.data.api.APIError: gsrsearch-error

### ISSUE THREAD

**Issue by urbanecm** [matejsuchanek/pywikibot-scripts#1]
Ahoj Matěji, 
zkusil jsem ten skript `typos.py` spustit (pomocí `python typos.py` v naklonovaném repozitáři). Evidentně jsem ho buď spouštěl blbě, anebo je něco s tím skriptem. 

== Výstup skriptu ==
Expression matched title: Žlutý pes
No results from query insource:/himal[aá]j/i
Doing insource:/him[aá]l[aá]jemi/i
Expression matched title: Alois Musil
Expression matched title: Berlínské krize
Expression matched title: Brahmaputra
Expression matched title: Hulevník vysoký
Expression matched title: Petr Sirotek
Expression matched title: Puncak Jaya
Expression matched title: Sandó Kaisen
No results from query insource:/him[aá]l[aá]jemi/i
Doing insource:/honorál/i
No results from query insource:/honorál/i
Doing insource:/hardvardská univer/i
No results from query insource:/hardvardská univer/i
Doing insource:/hardvardské [^ ]+ity/i
No results from query insource:/hardvardské [^ ]+ity/i
Doing insource:/hardvardské [^ ]+itě/i
No results from query insource:/hardvardské [^ ]+itě/i
Doing insource:/hardvardskou [^ ]+itu/i
No results from query insource:/hardvardskou [^ ]+itu/i
Doing insource:/hardvardskou [^ ]+itou"/i
WARNING: API error gsrsearch-error: Regular expression syntax error at 23: expected &#39;&#34;&#39;
Traceback (most recent call last):
  File "typos.py", line 91, in <module>
    for page in pagegenerators.SearchPageGenerator(rule[0], namespaces=[0], site=site):
  File "/home/martin/bin/pywikibot/pywikibot/pagegenerators.py", line 2278, in SearchPageGenerator
    for page in site.search(query, total=total, namespaces=namespaces):
  File "/home/martin/bin/pywikibot/pywikibot/data/api.py", line 2744, in **iter**
    self.data = self.request.submit()
  File "/home/martin/bin/pywikibot/pywikibot/data/api.py", line 2188, in submit
    raise APIError(**result['error'])
pywikibot.data.api.APIError: gsrsearch-error: Regular expression syntax error at 23: expected &#39;&#34;&#39; [help:See https://cs.wikipedia.org/w/api.php for API usage]
<class 'pywikibot.data.api.APIError'>
CRITICAL: Closing network session.

**Comment by matejsuchanek** [comment]
Ahoj, díky za zprávu. Chyba byla v přebytečném znaku [přímo v seznamu překlepů](https://cs.wikipedia.org/w/index.php?title=Wikipedie:WPCleaner/Typo&diff=14019293&oldid=13997328).

**Comment by urbanecm** [comment]
Díky za opravu!

**Comment by urbanecm** [comment]
@matejsuchanek Jedná se u následujícího outputu o stejný případ?

== Output ==
Expression matched title: Sluneční energie
Expression matched title: Transformátor
Expression matched title: Univerzitní informační systém Mendelovy univerzity v Brně
Expression matched title: Vlnový multiplex
Expression matched title: Westland Wapiti
Expression matched title: Zakarpatská oblast
Expression matched title: Zdravotní rizika kouření tabáku
Expression matched title: Zmatek na Parnasu
Expression matched title: Čísla Nepustia
Expression matched title: Řež (hra)
No results from query insource:/[ ]neni[ ]/i
Doing insource:/nešťovic/i
No results from query insource:/nešťovic/i
Doing insource:/n[eě]š[tť]asn/i
Expression matched title: Brusilovova ofenzíva
Expression matched title: Hraběnka (opera)
Expression matched title: Wang Š’-čen
No results from query insource:/n[eě]š[tť]asn/i
Doing insource:/nevin[áéý]/i
Expression matched title: Ad tuendam fidem
Expression matched title: Nakam
No results from query insource:/nevin[áéý]/i
Doing insource:/new[ -]?yorksk/i
WARNING: API error gsrsearch-error: Regular expression syntax error at 14: expected &#39;&#93;&#39;
Traceback (most recent call last):
  File "typos.py", line 91, in <module>
    for page in pagegenerators.SearchPageGenerator(rule[0], namespaces=[0], site=site):
  File "/home/martin/bin/pywikibot/pywikibot/pagegenerators.py", line 2278, in SearchPageGenerator
    for page in site.search(query, total=total, namespaces=namespaces):
  File "/home/martin/bin/pywikibot/pywikibot/data/api.py", line 2744, in **iter**
    self.data = self.request.submit()
  File "/home/martin/bin/pywikibot/pywikibot/data/api.py", line 2188, in submit
    raise APIError(**result['error'])
pywikibot.data.api.APIError: gsrsearch-error: Regular expression syntax error at 14: expected &#39;&#93;&#39; [help:See https://cs.wikipedia.org/w/api.php for API usage]
<class 'pywikibot.data.api.APIError'>
CRITICAL: Closing network session.

**Comment by matejsuchanek** [comment]
[Ano](https://cs.wikipedia.org/w/index.php?title=Wikipedie:WPCleaner/Typo&diff=14019330&oldid=14019293).

**Comment by urbanecm** [comment]
Díky moc.
