### ISSUE TITLE
[typos.py] Návrh nové funkce - ukládání s potvrzením

### ISSUE THREAD

**Issue by urbanecm** [matejsuchanek/pywikibot-scripts#3]
Rád bych navrhl novou funkci, kdy bude k dispozici nějaký podobný přepínač jako u PWB -always, bez kterého se bude skript typos.py na každou editaci ptát, aby pak nedocházelo k situacím jako je https://cs.wikipedia.org/w/index.php?diff=14026013, anebo předtím https://cs.wikipedia.org/w/index.php?title=%C4%8Cesk%C3%BD_pravopis&diff=13263784&oldid=12999425 (v čemž je ale typos.py nevinně, protože to byl můj jednorázový skriptík na překlepy; každopádně princip je stejný).

Předem díky za doprogramování.

**Comment by matejsuchanek** [comment]
Něco jsem zkusil, kdyby to nefungovalo, "reopen and comment".

**Comment by urbanecm** [comment]
Ne že by úplně nefungovalo, ale zobrazuje to změny po kosmetických změnách a v některých článcích to dělá diff tak velkej, že se ten překlep nevejde na obrazovku. Nešlo by zobrazovat diff před kosmetickými změnami, jako to má například solve_disambiguation.py? {{Malé|Reopen and comment tu nemám, takže jsem na to neklikl. Mám to pouze ve vlastních repozitářích. }}

**Comment by matejsuchanek** [comment]
Pokud se dívám dobře, tak [kosmetické změny se volají](https://github.com/wikimedia/pywikibot-core/blob/master/pywikibot/page.py#L1216) uvnitř `page.save()`, tedy až potom, [co ukazuju diff](https://github.com/matejsuchanek/pywikibot-scripts/blob/master/typos.py#L129). Podezřelý mi přijde [tento řádek v kosmetických změnách](https://github.com/wikimedia/pywikibot-core/blob/master/pywikibot/cosmetic_changes.py#L280), jinak nevím...

**Comment by matejsuchanek** [comment]
Mám to, může za to oprava " <ref" na "<ref"...
